use tracing::error;

use crate::{
    common::{
        bus::Bus,
        types::{Byte, Cycles},
    },
    cpu::{Cpu, load},
};

pub fn execute<B: Bus>(cpu: &mut Cpu, bus: &mut B, opcode: Byte) -> Cycles {
    match opcode {
        0x01 => load::ld_bc_n16(cpu, bus),
        0x02 => load::ld_bc_a(cpu, bus),
        0x06 => load::ld_b_n8(cpu, bus),
        0x08 => load::ld_n16_sp(cpu, bus),
        0x0A => load::ld_a_bc(cpu, bus),
        0x0E => load::ld_c_n8(cpu, bus),
        0x11 => load::ld_de_n16(cpu, bus),
        0x12 => load::ld_de_a(cpu, bus),
        0x16 => load::ld_d_n8(cpu, bus),
        0x1A => load::ld_a_de(cpu, bus),
        0x1E => load::ld_e_n8(cpu, bus),
        0x21 => load::ld_hl_n16(cpu, bus),
        0x22 => load::ld_hli_a(cpu, bus),
        0x26 => load::ld_h_n8(cpu, bus),
        0x2A => load::ld_a_hli(cpu, bus),
        0x2E => load::ld_l_n8(cpu, bus),
        0x31 => load::ld_sp_n16(cpu, bus),
        0x32 => load::ld_hld_a(cpu, bus),
        0x36 => load::ld_hl_n8(cpu, bus),
        0x3A => load::ld_a_hld(cpu, bus),
        0x3E => load::ld_a_n8(cpu, bus),
        0x40 => load::ld_b_b(cpu),
        0x41 => load::ld_b_c(cpu),
        0x42 => load::ld_b_d(cpu),
        0x43 => load::ld_b_e(cpu),
        0x44 => load::ld_b_h(cpu),
        0x45 => load::ld_b_l(cpu),
        0x46 => load::ld_b_hl(cpu, bus),
        0x47 => load::ld_b_a(cpu),
        0x48 => load::ld_c_b(cpu),
        0x49 => load::ld_c_c(cpu),
        0x4A => load::ld_c_d(cpu),
        0x4B => load::ld_c_e(cpu),
        0x4C => load::ld_c_h(cpu),
        0x4D => load::ld_c_l(cpu),
        0x4E => load::ld_c_hl(cpu, bus),
        0x4F => load::ld_c_a(cpu),
        0x50 => load::ld_d_b(cpu),
        0x51 => load::ld_d_c(cpu),
        0x52 => load::ld_d_d(cpu),
        0x53 => load::ld_d_e(cpu),
        0x54 => load::ld_d_h(cpu),
        0x55 => load::ld_d_l(cpu),
        0x56 => load::ld_d_hl(cpu, bus),
        0x57 => load::ld_d_a(cpu),
        0x58 => load::ld_e_b(cpu),
        0x59 => load::ld_e_c(cpu),
        0x5A => load::ld_e_d(cpu),
        0x5B => load::ld_e_e(cpu),
        0x5C => load::ld_e_h(cpu),
        0x5D => load::ld_e_l(cpu),
        0x5E => load::ld_e_hl(cpu, bus),
        0x5F => load::ld_e_a(cpu),
        0x60 => load::ld_h_b(cpu),
        0x61 => load::ld_h_c(cpu),
        0x62 => load::ld_h_d(cpu),
        0x63 => load::ld_h_e(cpu),
        0x64 => load::ld_h_h(cpu),
        0x65 => load::ld_h_l(cpu),
        0x66 => load::ld_h_hl(cpu, bus),
        0x67 => load::ld_h_a(cpu),
        0x68 => load::ld_l_b(cpu),
        0x69 => load::ld_l_c(cpu),
        0x6A => load::ld_l_d(cpu),
        0x6B => load::ld_l_e(cpu),
        0x6C => load::ld_l_h(cpu),
        0x6D => load::ld_l_l(cpu),
        0x6E => load::ld_l_hl(cpu, bus),
        0x6F => load::ld_l_a(cpu),
        0x70 => load::ld_hl_b(cpu, bus),
        0x71 => load::ld_hl_c(cpu, bus),
        0x72 => load::ld_hl_d(cpu, bus),
        0x73 => load::ld_hl_e(cpu, bus),
        0x74 => load::ld_hl_h(cpu, bus),
        0x75 => load::ld_hl_l(cpu, bus),
        0x77 => load::ld_hl_a(cpu, bus),
        0x78 => load::ld_a_b(cpu),
        0x79 => load::ld_a_c(cpu),
        0x7A => load::ld_a_d(cpu),
        0x7B => load::ld_a_e(cpu),
        0x7C => load::ld_a_h(cpu),
        0x7D => load::ld_a_l(cpu),
        0x7E => load::ld_a_hl(cpu, bus),
        0x7F => load::ld_a_a(cpu),
        0xC1 => load::pop_bc(cpu, bus),
        0xC5 => load::push_bc(cpu, bus),
        0xD1 => load::pop_de(cpu, bus),
        0xD5 => load::push_de(cpu, bus),
        0xE0 => load::ldh_n8_a(cpu, bus),
        0xE1 => load::pop_hl(cpu, bus),
        0xE2 => load::ldh_c_a(cpu, bus),
        0xE5 => load::push_hl(cpu, bus),
        0xEA => load::ld_n16_a(cpu, bus),
        0xF0 => load::ldh_a_n8(cpu, bus),
        0xF1 => load::pop_af(cpu, bus),
        0xF2 => load::ldh_a_c(cpu, bus),
        0xF5 => load::push_af(cpu, bus),
        0xF8 => load::ld_hl_sp_e8(cpu, bus),
        0xF9 => load::ld_sp_hl(cpu),
        0xFA => load::ld_a_n16(cpu, bus),
        _ => {
            error!("Opcode {:#04X} not yet implemented", opcode);
            0
        }
    }
}

